# These are supported funding model platforms

github: No Funders
patreon: No Funders
open_collective: No Funders
ko_fi: No Funders
tidelift: No Funders
community_bridge: No Funders
liberapay: No Funders
issuehunt: No Funders
lfx_crowdfunding: No Funders
polar: No Funders
buy_me_a_coffee: No Funders
thanks_dev: No Funders
custom: No Funders
